### ISSUE TITLE
show audio player on lock screen

### ISSUE THREAD

**Issue by Ambrosiani** [NordicMuseum/Nordic-Museum-Audio-Guide#12]
Background audio is available since 6f6efa0fe69e561b93787821d5e97ac17b6c7ffe, but it would also be nice to have the player controls available on the lock screen.

**Comment by RubenSandwich** [comment]
Let's try this first:

https://stackoverflow.com/questions/48070705/cant-show-player-controls-on-ios-lock-screen

**Comment by Ambrosiani** [comment]
solved (with static description but hey, good enough) by 9b826ae4664adfe17b9465202f7589458a53debc!
