### ISSUE TITLE
LTR/RTL language switch not working 100 %

### ISSUE THREAD

**Issue by Ambrosiani** [NordicMuseum/Nordic-Museum-Audio-Guide#13]
Users report problems when switching btwn left-to-right and right-to-left languages. Todo: add screenshots here…

**Comment by Ambrosiani** [comment]
I think that the language setting is (sometimes) not stored correctly when the app is restarted. In the attached example, it reverts to the default phone language about 50 % of the time.

[Screen recording](url
https://github.com/NordicMuseum/Nordic-Museum-Audio-Guide/blob/master/readMe/assets/screenRecording20190313.MP4?raw=true)

**Comment by RubenSandwich** [comment]
Hmm thanks for the video @Ambrosiani did you find any steps that can reproduce it 100% of the time?

**Comment by Ambrosiani** [comment]
not yet, but will do some more serious testing on the ipods :)

**Comment by RubenSandwich** [comment]
Thanks so much Aaron!

**Comment by Ambrosiani** [comment]
on an iphone with Swedish as default locale:

1. remove app from cache
2. start app (in Swedish)
3. switch to Arabic

result:
Arabic, LTR: 1
Arabic, RTL: 5
Swedish, RTL: 3
Swedish, LTR: 5

on an iphone with Swedish as default locale & "museum mode"

1. remove app from cache
2. start app (in Swedish)
3. select Arabic in tutorial

result:
Arabic, LTR: 0
Arabic, RTL: 6
Arabic, some RTL & some LTR: 1
Swedish, RTL: 0
Swedish, LTR: 4
Swedish, some RTL & some LTR: 1
crashed app: 3

**Comment by RubenSandwich** [comment]
@Ambrosiani Awesome thanks for the detailed write-up. It's a bit crazy how all over the place this bug is... 😖  I'll look into it a bit next week.

**Comment by Ambrosiani** [comment]
seems like I18nManager.forceRTL & react-native-restart could be enough. That's how our KTH students implemented it in their android version at least.

**Comment by Ambrosiani** [comment]
no issues so far in v2 – closing!
