### ISSUE TITLE
Export from Google sheets to Javascript

### ISSUE THREAD

**Issue by Ambrosiani** [NordicMuseum/Nordic-Museum-Audio-Guide#15]
change data/tourStops.js into a tourJSON-compliant JSON file and either…

a) make a middleman transforming it back into the current data model
b) change the current data model and load the JSON into it

hopefully we can later on team up with @ericpugh at Smithsonian American Art Museum and make a drupal site that outputs tourJSON through its API.

**Comment by Ambrosiani** [comment]
after some discussion with @RubenSandwich this can be broken into a few parts which can then be changed into their own issues…

the overall goals are:

1) make the data editing more robust by adding a CMS that exports into the javascript object used by the app. In a first step, this could be adding some scripting to the existing google spreadsheets document used by the Nordic Museum. It could also be a drupal/directus/something else installation with a JSON API.

2) increase interoperability by using a more generalized JS object format. One possible solution is tourJSON (an adaptation of TourML into JSON). This would – in theory! – make it easier for multiple institutions to use the code since they – again, in theory – might already have tourJSON-compliant audio tour data. It also means that if someone else puts together a CMS (goal 1) that outputs tourJSON it can be used by this app.

3) allow over-the-air content updates of the app. This would reduce the number of times the app needs to be updated which helps a lot when using ipods with Single App Mode. Currently, these need to be manually unlocked for an app update to take place as the Single App Mode overrides the automatic app updates setting in iOS.

**Comment by Ambrosiani** [comment]
in the current project: add scripting to the existing google spreadsheets document used by the Nordic Museum to export into JS

**Comment by RubenSandwich** [comment]
@Ambrosiani Can you provide an example google sheets file that I have access to is in the same format as your spreadsheet so I can start work on this?

**Comment by Ambrosiani** [comment]
@RubenSandwich here's a clean version of the one we used: https://docs.google.com/spreadsheets/d/1QBR5Bg1Hq6GvBzNmct3KInwUjDJEvKgb-qJnLrykh3I/edit#gid=0

**Comment by RubenSandwich** [comment]
@Ambrosiani Looking through the spreadsheet how do you know which Stops fall into which Tours?

**Comment by Ambrosiani** [comment]
column E, "tour". Manual cutting and pasting to get the highlights tour though (the first one in tourStops.js, beginning at line 7. https://github.com/NordicMuseum/Nordic-Museum-Audio-Guide/blob/761bf4258f2fc63da342e2bc89103517651e4f61/app/data/tourStops.js#L7

i.e. to get everything else, I used the "Tours" sheet and column R, then pasting the corresponding stops from sheet "Stops", column AI into each tour.
