### ISSUE TITLE
separate interface & content strings in localization data

### ISSUE THREAD

**Issue by Ambrosiani** [NordicMuseum/Nordic-Museum-Audio-Guide#16]
data/strings.js contains both interface & content strings. Ideally we should separate these and move the content strings into the tourJSON model.

**Comment by sticknor** [comment]
Plan to remove unused fields from  tour stop model (except transcripts which is a future goal)

**Comment by Ambrosiani** [comment]
@sticknor awesome! There's some museum specific content in the UIStrings, let's look at how to split that file on Wednesday.
