### ISSUE TITLE
remove html2jsx from utilities

### ISSUE THREAD

**Issue by Ambrosiani** [NordicMuseum/Nordic-Museum-Audio-Guide#18]
Should we get rid of the html2jsx utility function and replace it with something more robust? Can we use react-native-simple-markdown instead?

**Comment by Ambrosiani** [comment]
priority: low since html2jsx is used in the Warhol app but not in the Nordic Museum app.

**Comment by RubenSandwich** [comment]
Your right. Let's update this issue to remove this code then.
