### ISSUE TITLE
Setup continuous deployment Github > App Store

### ISSUE THREAD

**Issue by Ambrosiani** [NordicMuseum/Nordic-Museum-Audio-Guide#19]
To be described in more detail.

**Comment by RubenSandwich** [comment]
Using something like https://appcenter.ms? Or just build on TravisCI/CircleCI and https://fastlane.tools.

**Comment by Ambrosiani** [comment]
Fastlane looks like a good first choice – since we are adding the mp3 files manually we can't move completely into the cloud yet anyway.

**Comment by RubenSandwich** [comment]
@Ambrosiani One way to completely move to the cloud is for a private repo of the copyrighted mp3's and images living in a private repo and during the CD process, those assets can be placed in the app before building and submitting to the app store. (Both Travis and CircleCI support having secrets, like a GitHub token, in your CI/CD service.) I think we should at least explore this route and try to save you the ~1 hour it takes per release.

**Comment by Ambrosiani** [comment]
- [ ] set up builds for ios and android
- [ ] https://docs.microsoft.com/sv-se/appcenter/build/ios/uploading-signing-files
- [ ] replace placeholder files with ones from private repo

**Comment by Ambrosiani** [comment]
@RubenSandwich doesn't seem like I can combine assets from multiple repositories. rather, should we push changes from the public repo into the private repo and then build from the private repo?

**Comment by RubenSandwich** [comment]
Yeah let’s try that.

Can you also contact App Center and see if they will upgrade us because
it’s a non-profit?

Ruben

P.S. Is there anyway to run a script before building?

**Comment by Ambrosiani** [comment]
@RubenSandwich yes, scripts can run post-clone, pre-build & post-build.

https://docs.microsoft.com/en-us/appcenter/build/custom/scripts/

I'll contact them!

for syncing btwn the two repositories, do you think something like https://github.com/livechat/copycat is a good idea? (first result from googling)

**Comment by RubenSandwich** [comment]
Hmm,

I'd actually lean more towards just using a pre-build script to move the
required file over.
(Those scripts should be easy to write and I'll write once everything is
set up correctly. Is the normal build working for you yet?)
I think that would be easier than trying to keep two repos in sync.

Do you know if when we run the build script does it have access to the
assets repo?

Ruben

**Comment by Ambrosiani** [comment]
trying a post-clone script now that clones the private assets into the correct folder. Might even work :)

**Comment by Ambrosiani** [comment]
@RubenSandwich builds fine, but it seems I need to add an ad-hoc provisioning profile rather than the distribution profile. Will try that tomorrow!

**Comment by Ambrosiani** [comment]
@RubenSandwich as far as I can tell it works for iOS now. Build gets submitted to Testflight & we should be able to publish from there. I'll set Appcenter to increment the build number automatically as well. I bumped the version to 2.0. Will take a look at android now.

**Comment by RubenSandwich** [comment]
@Ambrosiani,

Few updates for your post-clone script:

(The first two are the secrets for our App Center Analytics. You can test if it works by launching the App and seeing if the "Active Devices" in the App Center Analytics goes up.)
* copy:
 **Nordic-Museum-Audio-Guide-Assets/secrets/appcenter-config.json** 
over the file:
**Nordic-Museum-Audio-Guide/v2/android/app/src/main/assets/appcenter-config.json**
* copy:
**Nordic-Museum-Audio-Guide-Assets/secrets/AppCenter-Config.plist** 
over the file: 
**Nordic-Museum-Audio-Guide/v2/ios/AppCenter-Config.plist**
* Run:
**npm run transfer-assets-android** 
from the v2 root directory to copy over the final Android assets. 
(Run this after moving in the final assets.)

Also are you sure that your the testflight builds works?

**Comment by Ambrosiani** [comment]
@RubenSandwich I put npm run transfer-assets-android in a second "pre-build" script which – if I understand everything correctly – runs after `npm i` (while post-clone runs before dependencies are installed). Testing now!

**Comment by RubenSandwich** [comment]
Okay just as long as the final assets are already loaded. Android needs the
audio files to be in a very exact location and name format which is what
that script that I wrote does. Let me know if it works and if not how it’s
breaking.

**Comment by Ambrosiani** [comment]
@RubenSandwich hm, the first build made it to the App Store but not the later ones. When running the same scripts locally & then building, asset loading & appcenter analytics work as expected.

**Comment by RubenSandwich** [comment]
@Ambrosiani Strange. What error is it giving you? I also logged into App Center, went to build 8 and manually told it to push that build to TestFlight. When I did that I got the error:

> Oh no! Build 8 failed to distribute. Error: Bad Gateway: undefined

It looks like their push is having troubles: https://status.appcenter.ms. 🤦‍♀

**Comment by Ambrosiani** [comment]
@RubenSandwich seems like Appcenter prefers manual signing. I'll try the steps outlined here:

https://intercom.help/appcenter/en/articles/1617765-ios-signing-issues-explained

**Comment by RubenSandwich** [comment]
@Ambrosiani Hmm. Okay. We can return this time, just as long as you can build and submit to the store.

How is setting up the Android CD going?

**Comment by Ambrosiani** [comment]
have switched from automatic to manual signing for iOS now, uploading a local build to the app store now before testing in Appcenter again.

Also doing my first run at an android release build. Need to upload it the Play Console before I can add the appcenter integration.
