### ISSUE TITLE
Update UI Screens For RN 60

### ISSUE THREAD

**Issue by sticknor** [NordicMuseum/Nordic-Museum-Audio-Guide#26]
To work, same as before, with RN 60:
- [x] Basic Root

- [x] Basic Tutorial 

- [x] Basic Settings

- [x] Everything -> Tours List

- [x] Tour Stop

- [ ] Bottom Player

- [x] Museum

- [x] Near Me

- [x] Amenities

- [x] Search By Number

**Comment by sticknor** [comment]
- [ ] Root

- [ ] Tutorial 

- [ ] Settings

**Comment by Ambrosiani** [comment]
@sticknor the only thing of note here is to consider the possibility of 3- or 4-digit numbers on the tourstops, see #14.
