### ISSUE TITLE
Update React Native to v0.X.X, after new module system

### ISSUE THREAD

**Issue by RubenSandwich** [NordicMuseum/Nordic-Museum-Audio-Guide#6]
Because of the large gap in the React Native version of this project and that latest React Native version the `react-native-git-upgrade` fails. So a new React Native project needs to be created and then all of the previous code and dependencies brought back in, updated, and tested.

This work will happen on the branch: **React-Native-v0.X.X**

Updates required:
- [ ] Native Modules need to use new React Native imports
  - [ ] Move away from custom Native Modules
    - [ ] CMSRTLManager (The forceReload method will most likely be broken as it depends on React Native internals.)
    - [ ] CMSBeaconManagerBridge
    - [ ] CMSAudioManager
    - [ ] CMSAccessibilityManager
  - [ ] Update Native Module dependencies
    - [ ] react-native-i18n
    - [ ] react-native-device-info
    - [ ] react-native-google-analytics-bridge
    - [ ] react-native-navigation
- [ ] Entry into an Android app (Just a stub for now.)
- [ ] Flexbox now defaults to flex: 1, which could cause breaking views
- [ ] Rename project to NordicMuseumAudioGuide

**Comment by Ambrosiani** [comment]
can you rename the project to NordicMuseumAudioGuide at the same time?

**Comment by Ambrosiani** [comment]
…awaiting whatever happens in 2019: https://github.com/react-native-community/discussions-and-proposals/issues/4

**Comment by Ambrosiani** [comment]
react-native-i18n is replaced by https://github.com/react-native-community/react-native-localize

**Comment by RubenSandwich** [comment]
@Ambrosiani Is there a certain feature the react-native-localize has that react-native-i18n is missing?

**Comment by Ambrosiani** [comment]
not sure, only saw the deprecation notice over at https://github.com/AlexanderZaytsev/react-native-i18n

**Comment by RubenSandwich** [comment]
@Ambrosiani Oh super lame, they must have added that since I last saw it. Fair enough, we should move from a deprecated package.
